// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           35
// Async Callback:                       1
// Total number of exported functions:  38

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    ticketing
    (
        init => init
        upgrade => upgrade
        buyTicket => buy
        issueFreeTicket => giveaway
        issuePaidTicket => giveaway_admin
        setFees => set_cut_fees
        getAllEvents => events
        getEvent => event_by_id
        getAllTicketTypes => ticket_types
        getTicketType => ticket_type_by_id
        getTicketStages => ticket_stages
        getAllowedUsers => whitelist_wallets
        buysPerEvent => buys_per_event
        buysPerTicketType => buys_per_ticket_type
        buysPerTicketStage => buys_per_ticket_stage
        getNonce => next_nonce
        collections => collections
        getTokenByEventId => token_manager
        getFees => fees
        getIncome => income
        isWhitelisted => is_whitelisted
        getEvents => get_events
        getTypes => get_types
        getTypeStages => get_type_stages
        getAllStages => get_all_stages
        getAllIncomeTokens => get_all_income_tokens
        getIncomePayment => get_all_income_payments
        whitelistSize => whitelisted_size
        createEvent => create_event
        createTicketType => create_ticket_type
        createTicketStage => create_ticket_stage
        removeTicketType => remove_ticket_type
        removeTicketStage => remove_ticket_stage
        editTicketType => edit_ticket_type
        editTicketStage => edit_ticket_stage
        addWhitelists => add_to_whitelist
        removeWhitelists => remove_from_whitelist
    )
}

multiversx_sc_wasm_adapter::async_callback! { ticketing }
